### ISSUE TITLE
Search for mods by project ID

### ISSUE THREAD

**Issue by Un1q32** [PolyMC/PolyMC#494] opened 2022-04-26 19:56 UTC
### Role

I play modded mc

### Suggestion

I want to be able to put a mods project ID into the search bar of the mod downloader, and get the result

### Benefit

It will be useful for when the mod updater is implemented, if we can't find a way to make it automatically find manually installed mods.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment] 2022-07-15 12:16
hmn, https://github.com/PolyMC/PolyMC/issues/726 seems more complete

**Comment by txtsd** [comment] 2022-07-15 19:25
duplicate of #726

**Closed as not planned by txtsd** 2022-07-15 19:25 UTC
Labels: enhancement
