### ISSUE TITLE
Shared Instance Files

### ISSUE THREAD

**Issue by jdev082** [PolyMC/PolyMC#1096] opened 2022-08-28 22:26 UTC
### Role

Mods, resource packs, worlds. I don't like copying files constantly!

### Suggestion

Have an option to make certain files shared between instances.

### Benefit

So I don't have to copy packs and mods I use on all versions!

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I'm going to get a bit more in-depth here. There can be 2 or both methods of marking shared files.

1. By right clicking an item in the mods, resource packs, worlds, or shaders section of the instance options, you can click "Make shared file" or something of the like.

2. Make a directory in the instances folder called 'shared' in which those files will span all instances.

**Comment by ZekeZDev** [comment] 2022-09-03 07:36
Duplicate of #73 hopefully this will be addressed soon.

**Closed as completed by ZekeZDev** 2022-09-03 07:36 UTC
Labels: enhancement
