### ISSUE TITLE
Move polymc.org off of Epik

### ISSUE THREAD

**Issue by Cynosphere** [PolyMC/PolyMC#177] opened 2022-02-17 21:56 UTC

**Comment by Scrumplex** [comment] 2022-02-17 22:08
We are aware that the registrar is controversial. We plan to switch to a different one but are currently unable to transfer (domain is not older than 60 days)

The domain was registered by our former head maintainer. We discussed internally that it would be better to switch to a different registrar.

We are probably going to move to porkbun.com

**Comment by Scrumplex** [comment] 2022-02-17 22:11
We will be able to switch in a few days.
See https://whois.domaintools.com/polymc.org

**Comment by Scrumplex** [comment] 2022-02-17 22:13
(This was decided a few weeks ago already. We just couldn't do it yet)

**Comment by Cynosphere** [comment] 2022-02-17 22:20
Thank you for actually working forward to make change instead of doubling down like I expected was going to happen. Hopefully the same action will happen towards the community as well as some members in the chat rooms were acting very problematic when someone else brought this up.

Hopefully this project can get more positive reputation back instead of the negative it seems to be heading because of all of this.

**Comment by Scrumplex** [comment] 2022-02-17 22:23
Yeah I read the conversation in the chat. I am sorry about that. If I had reacted earlier it probably wouldn't have come to this. We def. need more moderation. But at least we have an issue to point people to in case they mention the current registrar.

I want to add that you haven't spoken with any maintainer or contributor on the Discord. So what was written there does not represent the views of the "Core Team" (see Members list of this GitHub organization)

**Comment by ghost** [comment] 2022-02-18 01:46
I still don't really understand the problem with Epik other than that Wikipedia hates it, but at this point I don't care enough about the situation to care about reasonings anymore

**Comment by clydebottoms** [comment] 2022-02-21 18:55
using companies that store ssh keys in plaintext to host your platform might not be a good idea but that's just my opinion

**Comment by ghost** [comment] 2022-02-22 02:44
> using companies that store ssh keys in plaintext to be your domain registrar might not be a good idea but that's just my opinion

Epik does that? Wtf I love Epik now. Never switching

**Comment by ghost** [comment] 2022-02-22 02:45
In other news, for chads who love Epik, [SneedMC](https://github.com/Sneederix/SneedMC)'s website sneedmc.org is registered through Epik. Based!

**Comment by clydebottoms** [comment] 2022-02-22 02:49
Sneed

**Comment by HalJordan** [comment] 2022-02-23 01:03
> using companies that store ssh keys in plaintext to be your domain registrar might not be a good idea but that's just my opinion

C'mon, you can't share something like that w/o a link.

**Comment by d-513** [comment] 2022-02-23 09:10
Good news, the transfer is initiated now we’re waiting for it to finish they say it can take up to 5 days

**Comment by ghost** [comment] 2022-02-23 12:45
At the absolute earliest I will have the time to do this on Sunday, even that I doubt though due to the amount of school work I still need to make up.

**Comment by LennyMcLennington** [comment] 2022-02-23 12:52
> At the absolute earliest I will have the time to do this on Sunday, even that I doubt though due to the amount of school work I still need to make up.

That is a lie, you had no issue locking the domain in preparation for the transfer, setting the correct name servers and unlocking the domain takes one minute max, and if you have time to comment on github issues you have time to do that.

Stop stalling.

**Comment by Scrumplex** [comment] 2022-02-23 12:54
The process is as follows:
- Unlock domain at Epik
- Get auth code from Epik
- Start transfer at new registrar

WHOIS says that the domain is locked right now, so I am confused as I thought the transfer was initiated already..
https://whois.domaintools.com/polymc.org

**Comment by LennyMcLennington** [comment] 2022-02-23 12:55
> The process is as follows:
> 
> * Unlock domain at Epik
> * Get auth code from Epik
> * Start transfer at new registrar
> 
> WHOIS says that the domain is locked right now, so I am confused as I thought the transfer was initiated already.. https://whois.domaintools.com/polymc.org

The domain was unlocked, I was given the auth code, I told swurl to lock the domain so I would have time to set up the DNS records on porkbun before the domain was transferred, I told him a few hours later (still on 21st of feb) that it was ready to transfer so he can set the nameservers and unlock it, and he still hasn't done that.

**Comment by Scrumplex** [comment] 2022-02-23 12:56
In case this doesn't get resolved quickly I will offer an alternative domain for our use.

**Comment by ghost** [comment] 2022-02-23 20:13
> > At the absolute earliest I will have the time to do this on Sunday, even that I doubt though due to the amount of school work I still need to make up.
> 
> That is a lie, you had no issue locking the domain in preparation for the transfer, setting the correct name servers and unlocking the domain takes one minute max, and if you have time to comment on github issues you have time to do that.
> 
> Stop stalling.

Stop whining and I would've done it earlier. Because you won't shut up I've transferred the nameservers and unlocked it, which took 3 too many minutes that should've been spent on studying.

In other news, [SneedMC](https://github.com/Sneederix/SneedMC) still uses Epik. Based!

**Comment by nonetrix** [comment] 2022-02-26 05:03
I would say Epik is fine besides the data breach they don't ban websites just because you said something they don't like just my take though

**Comment by Realswitzer** [comment] 2022-02-26 16:19
I struggle to see the problem with Epik.

**Comment by Scrumplex** [comment] 2022-03-01 12:10
Starting today the domain is officially not registered at Epik anymore! 🎉 

Additionally we have moved essential infrastructure (`meta.polymc.org` and related services) to GitHub Pages to ensure auditability and reproducibility.

**Closed as completed by Scrumplex** 2022-03-01 12:10 UTC
Labels: priority, external
