### ISSUE TITLE
Steam input only using "Desktop configuration" when playing the game through PolyMC

### ISSUE THREAD

**Issue by ethan021021** [PolyMC/PolyMC#874] opened 2022-07-05 00:36 UTC
### Version of PolyMC

1.3.2-404

### Description of bug

I expected to be able to play the game with my steam input settings but it seems that does not work.

### Steps to reproduce

1. Boot steam deck into desktop mode
2. Launch PolyMC 
3. Open an instance
4. Try playing the game with a steam controller
5. Notice you can't move with the Joystick

### Suspected cause

Steam

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kthchew** [comment] 2022-07-06 04:42
Possible duplicate of #302

If you'd like, you can give the fix in that issue a try

**Comment by ethan021021** [comment] 2022-07-16 02:05
That worked! Is there anyway to incorporate runpolymc.sh into the flatpak? Thanks!

**Comment by kthchew** [comment] 2022-07-16 20:31
#893 should fix this issue for all install methods. The fix will likely be present in 1.4.0.

**Closed as completed** 2022-07-23 12:08 UTC
Labels: bug
