### ISSUE TITLE
Updater in launcher

### ISSUE THREAD

**Issue by MofumofuChan** [PolyMC/PolyMC#1041] opened 2022-08-10 17:24 UTC
So, when I went to update PolyMC, I noticed that I needed to download it again. Isn't it possible to automatically update it for you in the click of a button like MultiMC does?

**Comment by DioEgizio** [comment] 2022-08-10 17:25
Duplicate of #60

**Comment by timoreo22** [comment] 2022-08-10 17:25
Not yet, on mac there is one, on linux it is not needed but not yet for windows

**Closed as not planned by timoreo22** 2022-08-10 17:25 UTC
