### ISSUE TITLE
Fabric Legacy support

### ISSUE THREAD

**Issue by orvitpng** [PolyMC/PolyMC#886] opened 2022-07-08 02:45 UTC
### Role

Separating my different modpack and vanilla profiles.

### Suggestion

I want to be able to install Fabric Legacy into one of my profiles inside of the launcher.

### Benefit

This will allow users to run Fabric mods in pre-1.13 versions of Minecraft, and more personally, allows me to run my legacy mods.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment] 2022-07-08 06:15
Duplicate of #109

**Closed as not planned** 2022-07-08 14:59 UTC
Labels: enhancement

**Comment by orvitpng** [comment] 2022-07-08 16:47
Hmm, this is not the first time GitHub search has failed me.
