### ISSUE TITLE
Unable to detect the forge installer!

### ISSUE THREAD

**Issue by Zatan16** [PolyMC/PolyMC#1638] opened 2024-01-14 17:47 UTC
My minecraft instance (offline) is not able to detect the forge installer I then tried to install it but any method of trying to install wasn't working. So, are there any PolyMC specific methods that I should try to install the forge installer. I tried to make an instance without selecting the forge option and it worked perfectly (and laggy, that's the only reason I need forge, for OptiFine)

This is the error that I am getting:
```
SEVERE: Exception caught from launcher.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.RuntimeException: Unable to detect the forge installer!
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:136)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:115)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:147)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:29)
	... 9 more
Jan 14, 2024 10:47:19 PM org.polymc.EntryPoint main
INFO: Exiting with 1
Process exited with code 1.
```

**Comment by ghost** [comment] 2024-01-14 18:37
What ways did you try to install?
Does Fabric with, e.g. Fabulously Optimized work?

**Comment by Zatan16** [comment] 2024-01-15 04:43
I installed the JAR file and then tried to allow executing permissions but there was no such option to allow executing.
I tried using `sudo chmod +x filename` to allow the executing permissions but still, it wouldn't execute
And then I used `java -jar filename` to run it and it worked, but when I selected the .minecraft folder of my instance, it said `The directory is missing a launcher profile. Please run the minecraft launcher first.` and it closed when I pressed "OK"
Edit: I also clicked on the "Install Forge" option and then selected "Download All" in the Edit Instance Menu but still am getting the same error.

**Comment by ghost** [comment] 2024-01-15 14:58
Okay. What happens when you create a new Vanilla 1.20.4 instance, select Edit Instance, then Install Forge, and install 49.0.19? Doing that has no issues for me.

For now though, I would highly recommend using Fabric with Fabulously Optimized, it's significantly better than OptiFine on top of being open-source. If installing Fabric fails as well, then you probably are lacking write permissions or something.

**Comment by Zatan16** [comment] 2024-01-15 16:15
Thank you, and one last thing. Does Fabulously Optimized have a feature where light blocks glow when in your hand and when dropped or do I need to manually install another mod for it? Also for the feature where I can zoom in to things.
Edit: I forgot to tell you, the former doesn't work but the latter does. Thank you for your help.

**Comment by ghost** [comment] 2024-01-15 18:29
> Thank you, and one last thing. Does Fabulously Optimized have a feature where light blocks glow when in your hand and when dropped or do I need to manually install another mod for it? Also for the feature where I can zoom in to things.
> Edit: I forgot to tell you, the former doesn't work but the latter does. Thank you for your help.

Ok, it might be worth it to investigate this further but since I can't reproduce there's not much I can do for now.

I forget if Fabulously Optimized includes it, but if not, I think LambdDynamicLights is what you need. I believe it needs Cloth Config as well, but I think that's included too.

**Comment by HeyaGlitz** [comment] 2024-01-19 14:29
@binex-dsk PolyMC depends on [Zeker's ForgeWrapper](https://github.com/ZekerZhayard/ForgeWrapper) for launching Forge, and he added support for 1.20.3 and 1.20.4 in [1.5.8](https://github.com/ZekerZhayard/ForgeWrapper/releases/tag/1.5.8) so the fix would be updating the ForgeWrapper on our meta server

**Comment by ghost** [comment] 2024-01-20 15:23
Where is this handled? I don't see it on any of the meta repos.

**Comment by HeyaGlitz** [comment] 2024-01-20 15:39
https://github.com/PolyMC/meta-scripts/blob/master/meta%2Fcommon%2Fforge.py
`FORGEWRAPPER_MAVEN` but I don't know how our maven works so you'll have to ask Lenny or something

**Comment by ghost** [comment] 2024-01-20 15:47
https://github.com/PolyMC/files/pull/2

**Comment by adamsong** [comment] 2024-02-11 02:07
I'm still seeing this after that pr was merged

**Comment by HeyaGlitz** [comment] 2024-02-11 02:11
There's something wrong with the meta server, Lenny is investigating it

**Comment by ghost** [comment] 2024-02-14 13:07
@adamsong the meta server as fixed, are you still facing issues or is everything good?

**Comment by adamsong** [comment] 2024-02-22 13:30
Sorry about the delay, still getting the error
```Feb 22, 2024 8:28:26 AM org.polymc.EntryPoint listen
SEVERE: Exception caught from launcher.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.RuntimeException: Unable to detect the forge installer!
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:157)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:136)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:170)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:38)
	... 9 more
Feb 22, 2024 8:28:26 AM org.polymc.EntryPoint main
INFO: Exiting with 1
```

**Comment by HeyaGlitz** [comment] 2024-02-22 15:04
from Lenny:
>first close PolyMC, then delete the folder `%AppData%/PolyMC/meta` and then it should work after re-opening PolyMC

**Comment by adamsong** [comment] 2024-02-22 15:08
Where is that on linux?

**Comment by HeyaGlitz** [comment] 2024-02-22 15:42
~/.local/share/PolyMC/

**Comment by adamsong** [comment] 2024-02-22 18:12
Works now, thanks

**Comment by XakepSDK** [comment] 2024-02-28 17:45
Doesn't work for me. Modpack Fear The Nightfall v12 from curseforge. I tried deleting polymc/meta directory. I'm using PolyMC 6.1 portable on windows.

**Comment by ghost** [comment] 2024-02-28 17:55
> Doesn't work for me. Modpack Fear The Nightfall v12 from curseforge. I tried deleting polymc/meta directory. I'm using PolyMC 6.1 portable on windows.

I can't remember off the top of my head, but it might be in PolyMC/files.

If not, post your error, it might give some clues

**Comment by XakepSDK** [comment] 2024-02-28 18:06
I don't have `PolyMC/files` directory, but I have `PolyMC/meta` directory. I tried deleting it, didn't help.
This directory `%AppData%/PolyMC/meta` does not exist.
Here is the error: https://gist.github.com/XakepSDK/2c1a1b2edf7d67087360eaf9772d3591

**Comment by ghost** [comment] 2024-02-28 21:47
Are you 100% sure that you closed PolyMC before deleting the directory?

**Comment by XakepSDK** [comment] 2024-02-28 21:48
Yes

**Comment by atzaveri** [comment] 2024-02-29 00:07
aparently polymc of any version stoped download forge installer, check under the folder: \libraries\net\minecraftforge\forge\1.19.2-43.3.5\ if you have forge-1.19.2-43.3.5-installer.jar 
btw, you can solve this just downloading the correct forge version > https://maven.minecraftforge.net/net/minecraftforge/forge/1.19.2-43.3.5/forge-1.19.2-43.3.5-installer.jar 
place on the folder and try again

**Comment by shroneko** [comment] 2024-02-29 02:45
I'm having the same issue trying to run forge modpacks from 1.19 and 1.20. Fabric modpacks work fine, so does vanilla mc.

```Feb 29, 2024 8:12:35 AM org.polymc.EntryPoint listen
SEVERE: Exception caught from launcher.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.RuntimeException: Unable to detect the forge installer!
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:157)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:136)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:170)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:38)
	... 9 more
Feb 29, 2024 8:12:35 AM org.polymc.EntryPoint main
INFO: Exiting with 1
Process exited with code 1. 
```
This is what the error code looks like and I'm pretty sure its a forge installer issue.

**Comment by Kaydax** [comment] 2024-02-29 05:38
This is most likely due to the fact every single forge installer has been updated, thus causing checksums to change and prob some other things. This was due to something on mojang's end where they decided to kill off one domain, causing every installer to just break

**Comment by Kaydax** [comment] 2024-02-29 06:26
I just made a PR that fixes the issue [here](https://github.com/PolyMC/files/pull/3). Now we just wait for Lenny to merge it and from there polymc should just work

**Comment by ghost** [comment] 2024-03-01 04:33
@XakepSDK @atzaveri @shroneko The PR's been merged. Try it now after deleting the meta directory.

**Comment by XakepSDK** [comment] 2024-03-01 13:46
It works! Thank you.

**Closed as completed** 2024-03-01 19:26 UTC
