### ISSUE TITLE
Add more options in mod updater

### ISSUE THREAD

**Issue by elchupe123** [PolyMC/PolyMC#1110] opened 2022-09-04 20:15 UTC
What i would like is a menu to change things like version of minecraft to search mods updates. For example instead of looking for new updates of a mod only for 1.19.1 to search new versions of a specific mod for 1.19.X.

**Comment by DioEgizio** [comment] 2022-09-05 06:49
Duplicate of #1031

**Comment by Scrumplex** [comment] 2022-09-06 09:24
As @DioEgizio mentioned, this is a duplicate.

**Closed as not planned by Scrumplex** 2022-09-06 09:24 UTC
Labels: duplicate
