### ISSUE TITLE
Infinite loop trying to log in to Minecraft

### ISSUE THREAD

**Issue by QazCetelic** [PolyMC/PolyMC#552] opened 2022-05-11 07:30 UTC
### Operating System

Linux

### Description of bug

The login starts looping, causing the entire computer to get stuck while cancelling shutdown procedure.

### Steps to reproduce

1. Launch instance

### Suspected cause

Issue caused by account migration.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment] 2022-05-11 13:05
wtf send logs (PolyMC-0.log)

**Comment by QazCetelic** [comment] 2022-05-11 13:11
I’m currently sitting in a crowded train so I can’t share the files right now, but I’ll describe a bit more what happened.

1. Instance Launched
2. Logging into Mojang account popup
3. Progress bar fills up
4. Popup closes
5. Popup reappears (back to step 2)

It’s impossible to close either PolyMC or the window during this and it blocks acces to other programs (such as System Monitor, the task manager of KDE Plasma).

**Comment by QazCetelic** [comment] 2022-05-11 14:32
> wtf send logs (PolyMC-0.log)

https://pastebin.com/r2RKC1Wn

**Comment by QazCetelic** [comment] 2022-05-11 14:33
I just looked at the log, and it seems like the logs contain the Microsoft auth token. Is this intended?

**Comment by DioEgizio** [comment] 2022-05-11 14:34
If you aren't using a debug build, switch to 1.2.2

**Comment by QazCetelic** [comment] 2022-05-11 15:37
I'll try that.
I won't be able to generate new log files, however, because I migrated to an MS account after encountering the issue.

**Comment by TheCodex6824** [comment] 2022-05-11 19:07
I had this happen to me once when I tried to start the game with a Mojang account before I finished my PR, but I thought that might have just been me messing something up because I was tinkering with the code. I would have to go back and look at the section of the code that handles that (which I won't have time for until in a few days, unfortunately), but my guess is that the launcher sees Yggdrasil succeeding but the profile fetch failing as a temporary failure and retries. Putting a cap on that is probably a good idea for the future, but using any version with the Mojang auth fix included should stop the infinite retrying for now.

**Comment by LennyMcLennington** [comment] 2022-05-12 17:26
If anyone wants to have a go at fixing this, one way to replicate it is to add a new entry to your /etc/hosts file: `0.0.0.0 api.minecraftservices.com` and then try to launch any instance. There's some loop logic that's supposed to make it just re-run some logic until it finishes in some way like launching the instance or erroring because the account is invalid. There's some issue with that logic that means it gets caught in an infinite loop when api.minecraftservices.com is down but other services are up. It should probably go to offline mode when that happens instead of infinitely retrying.

**Comment by Scrumplex** [comment] 2022-07-06 19:42
Duplicate of #85

**Closed as not planned by Scrumplex** 2022-07-06 19:42 UTC
Labels: bug
