### ISSUE TITLE
Issues showing the latest versions of mods

### ISSUE THREAD

**Issue by MechanosG** [PolyMC/PolyMC#1182] opened 2022-10-04 22:59 UTC
### Operating System

Windows

### Version of PolyMC

PolyMC 1.4.2 Legacy

### Version of Qt

Qt 5.15.5

### Description of bug

Basically, if you create a Quilt based modpack, then use the "Download mods" browser to search for mods, it seems to be unable to find Quilt mods most or all of the time, and instead only shows Fabric mods.  There seems to also be times where it's unable to find the latest Fabric mod version as well.

### Steps to reproduce

* Make a 1.19.2 Instance using Quilt
* Open the mods window for your instance, click Download mods
* Find a mod that has a Quilt specific version - as an example, lets use the mod Excavated Variants
* This is what shows in PolyMC as the latest version - ![polymc_E5q74abT2q](https://user-images.githubusercontent.com/4360512/193944834-ae811b9a-4622-4365-a50e-38e96694b61d.png)
* This is what's actually on Curseforge - 
![firefox_A6JxyQunFf](https://user-images.githubusercontent.com/4360512/193945191-2548042d-b9ca-4222-a673-aeeaa3e95565.png)
![firefox_8S43YXQy82](https://user-images.githubusercontent.com/4360512/193945204-7551b284-0bfa-477e-b974-9b6c81ff62aa.png)
* Click on the ca..

### Suspected cause

Seems to be defaulting to looking for Fabric mods only?

Disclaimer: I did search the issue tracker for a while and there does seem to be some related mentions to Quilt mods, but I am unsure if there is already a "unique" issue pertaining to this specifically.  I apologize if one already exists and I missed it.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Aces-and-Jacks** [comment] 2022-10-05 03:28
Not a developer or anything but when I tested it out it seems it's only an issue on curseforge. Tried it on modrinth and it worked. At least for excavated variants

**Comment by DioEgizio** [comment] 2022-10-05 05:18
Duplicate of #804 
It's not a bug, it's a not implemented feature. This can be closed.

**Closed as not planned** 2022-10-06 12:45 UTC
Labels: bug

**Comment by MechanosG** [comment] 2022-10-10 04:16
You seriously have no plans on making your mod browser look for Quilt mods, if it's Curseforge?  Like...  why?

I get it, Modrinth good.  But some mods aren't on Modrinth.  And the default mod browser has broken my modpack multiple times now, simply because it didn't check if a Quilt version existed.  I can't use the update check feature either, because it will try to overwrite Quilt mods with Fabric variants that aren't compatible.  There are surprisingly quite a few mods now that have independent versions for Quilt and Fabric.

I understand that it's entirely up to you.  But this seems like a very strange oversight/dismissal?  I must not understand something.  Like, maybe this would be difficult to implement?

**Comment by DioEgizio** [comment] 2022-10-10 05:46
We closed the issue as duplicate...

**Comment by MechanosG** [comment] 2022-10-10 05:56
```
@Scrumplex Scrumplex closed this as not planned
4 days ago
```
I took that as...  ..."not planned" lol.  I could have sworn github used to have a duplicate specific label.  Well anyway, I see you are discussing it in #804 .  I'll just see myself out.

**Comment by DioEgizio** [comment] 2022-10-10 06:02
not planned also means duplicate
