### ISSUE TITLE
Migrate from MultiMC to PolyMC

### ISSUE THREAD

**Issue by ghost** [PolyMC/PolyMC#359] opened 2022-03-28 12:47 UTC
### Role

I have a bunch of instances on MultiMC and I think it would be faster and better if there was a built-in migrate tool.

### Suggestion

I want a feature that allows you to migrate MultiMC instances over to PolyMC.

### Benefit

It helps with people first trying out PolyMC.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Scrumplex** [comment] 2022-03-28 13:03
Duplicate of #41 

The procedure is fairly simple and documented at https://polymc.org/wiki/getting-started/migrating-multimc/

**Closed as completed** 2022-03-28 13:03 UTC
