### ISSUE TITLE
Can't downlaod any CurseForge modpack

### ISSUE THREAD

**Issue by AnErrupTion** [PolyMC/PolyMC#658] opened 2022-05-28 08:56 UTC
### Operating System

Linux

### Version of PolyMC

PolyMC 1.3.0

### Description of bug

I can't download any modpack from CurseForge, and I know it worked in a previous version of PolyMC (but I forgot which one though). I tried with RLCraft and Project Ozone 1-2-3, yet it fails on downloading the mods. I know RLCraft was downloading successfully on older versions of PolyMC, but this is not the case anymore.

### Steps to reproduce

Download any modpack from CurseForge

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment] 2022-05-28 08:58
https://github.com/PolyMC/PolyMC/issues/593

**Comment by timoreo22** [comment] 2022-05-28 08:58
Duplicate of #593

**Closed as not planned by timoreo22** 2022-05-28 08:58 UTC
Labels: bug
