### ISSUE TITLE
Implement mod updater

### ISSUE THREAD

**Issue by ghost** [PolyMC/PolyMC#836] opened 2022-06-23 21:34 UTC
### Role

I play modded minecraft and create modpacks for personal use

### Suggestion

I would love an option similar to the download mods button, that updates mods the instance has downloaded

### Benefit

would allow for modpacks to be better kept to date without having to manually update each mod

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This would likely have to be exclusive to a certain modtype (curseforge, quilt, or fabric), and would require API access for both curseforge and modrinth (or just one or the other).

An implementation for this has existed as a fabric mod called [fabrilous updater](https://github.com/HughBone/fabrilous-updater), which has since been discontinued

**Comment by Scrumplex** [comment] 2022-06-23 21:43
Duplicate of #274 
Already being worked on in #588

**Closed as not planned by Scrumplex** 2022-06-23 21:43 UTC
Labels: duplicate, enhancement

**Comment by ghost** [comment] 2022-06-23 21:45
@Scrumplex sorry about that, I did a search and for some reason neither issues showed up :p

**Comment by Scrumplex** [comment] 2022-06-23 21:48
Don't worry :D

While my message above might look passive aggressive, it was just purely informational.
Duplicate issues are fairly rare anyway so they haven't become annoying yet :D
