### ISSUE TITLE
Trying to update multiple mods with no metadata occasionally crashes PolyMC

### ISSUE THREAD

**Issue by EssieFir** [PolyMC/PolyMC#1024] opened 2022-08-05 05:12 UTC
### Operating System

Windows

### Version of PolyMC

PolyMC 1.4.1

### Version of Qt

Qt 6.3.0

### Description of bug

When attempting to check for updates for all the mods in my mod list, after the confirmation prompt about metadata, PolyMC crashes after checking several mods.
This does not appear to happen for any specific mod as doing so individually does not result in a crash.

[PolyMC-1.log](https://github.com/PolyMC/PolyMC/files/9265482/PolyMC-1.log)

### Steps to reproduce

* Select an Instance (with a somewhat large amount of mods)
* Click View Mods
* Ctrl + A
* Click "Check for Updates"

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by stutsanks** [comment] 2022-08-05 06:07
try doing 2 or 3 mods updating at the same time. if it doesnt crash, maybe the problem is that theres too many mods to check. for me, im using the legacy version and works to update 100+ mods (dont ask why i have 100 mods).

**Comment by TayouVR** [comment] 2022-08-05 12:08
legacy is just Qt5 (vs Qt6, which dropped win7&8 support), I have been able to update 40 mods at once myself on non-legacy.

Looking at the log it seems, that the issue lies within generating metadata for mods which don't have any (e.g. that were added pre 1.4.0 (before the mod updater got added)). In this particular case it seems, that it struggles with FabricSkyBoxes. 
I personally can't tell why this happens, but i did observe similar behaviour with a older instance myself a bit ago.
In my case my conclusion was, that something didn't work with the disabled mods not having metadata.

My log from when that crash occured to me:
[PolyMC-0.log](https://github.com/PolyMC/PolyMC/files/9268373/PolyMC-0.log)

**Comment by EssieFir** [comment] 2022-08-05 16:46
> Looking at the log it seems, that the issue lies within generating metadata for mods which don't have any (e.g. that were added pre 1.4.0 (before the mod updater got added)). In this particular case it seems, that it struggles with FabricSkyBoxes. I personally can't tell why this happens, but i did observe similar behaviour with a older instance myself a bit ago. In my case my conclusion was, that something didn't work with the disabled mods not having metadata.

It definitely has something to do with generating mod metadata (though only in bulk).
Generating the metadata for all the mods (by updating the mods in small chunks) fixes the issue (for the updated instance).
The problem could still occur in 1.4+ if the user installs mods the old-fashioned way by directly putting them in the instances mod directory (several of which I did) and then trying to update them.

**Comment by flowln** [comment] 2022-08-05 21:21
Can you try seeing if the crash still occurs with a build from https://github.com/PolyMC/PolyMC/actions/runs/2805802674? For some reason I can't reproduce those crashes even with ~200 mod instances, but with a 400 one i managed to find some issues, though I'm not sure whether they're the cause of this one!

**Comment by EssieFir** [comment] 2022-08-06 04:27
PolyMC doesn't crash with that build

**Comment by flowln** [comment] 2022-08-28 11:17
Since #965 seems to have solved this, i'll close it for now. If there's more problems with it, feel free to re-open / send a message here!

**Closed as completed by flowln** 2022-08-28 11:17 UTC
Labels: bug
