### ISSUE TITLE
Implement  auto-download of  any required mod dependence (example: tinkers: mantle etc)

### ISSUE THREAD

**Issue by elchupe123** [PolyMC/PolyMC#896] opened 2022-07-09 22:05 UTC
### Role

I play minecraft with mods

### Suggestion

Implement  auto-download of any required mod dependence (example:  tinkers: mantle etc)

### Benefit

This would make a lot easier to download mods.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by flowln** [comment] 2022-07-09 22:39
Duplicate of #211

**Closed as not planned by flowln** 2022-07-09 22:39 UTC
Labels: duplicate, enhancement
