### ISSUE TITLE
Entire launcher (intermittently?) crashes when opening Forge 1.4.7 instance

### ISSUE THREAD

**Issue by quat1024** [PolyMC/PolyMC#986] opened 2022-07-27 06:50 UTC
### Operating System

Windows

### Version of PolyMC

1.4.0 (installed through `scoop`)

### Description of bug

When opening a Forge 1.4.7 instance with no mods in it, the launcher crashes to desktop.

### Steps to reproduce

1. Press "New instance", point it at vanilla 1.4.7 and Forge version 6.6.2.534 (the latest version for this mc version), "Ok"
2. Press "Edit instance" and ensure that the java installation points to Java 8 or whatever
3. Press "Launch".
4. The game log appears with the typical prelaunch pink log messages (DNS resolves, the java version checker, etc.)
5. The launcher crashes.

### Suspected cause

I don't know where PolyMC 1.4 writes its log files in non-portable mode, apparently it's a big secret and i can't find any documentation on the site about it lol. `polymc.exe | log.txt` doesn't seem to work for capturing logs into the file, they still go into the console.

I don't have LegacyJavaFixer or anything, but either way it should not be bringing down the *entire launcher*.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by timoreo22** [comment] 2022-07-27 07:04
Launcher's logs are in `%APPDATA%/PolyMC` if using the windows installer version, should be PolyMC-0.log please send it

**Comment by quat1024** [comment] 2022-07-27 07:08
Thanks, here's a log. https://paste.ee/p/5lmHy

In this session I created an instance called `1.4.7 forge testy test`, launched it successfully (surprise! even though it appeared as a regular vanilla instance with no signs of Forge, smh), closed it, launched it again, and the launcher crashed.

It's not truncated, the log really does end right there

**Comment by DioEgizio** [comment] 2022-07-27 07:22
I believe this is related to #956 
Can you try a develop build?

**Comment by timoreo22** [comment] 2022-07-27 07:30
Can reproduce on 1.4.0 build AND on develop build

**Comment by DioEgizio** [comment] 2022-07-27 07:34
Does it happen on a qt5 build?

**Comment by timoreo22** [comment] 2022-07-27 07:51
Can confirm happens on both qt5 and qt6

**Comment by Scrumplex** [comment] 2022-07-27 09:41
Hmm. I can't reproduce. Qt 6 build, `develop`, Linux

**Comment by txtsd** [comment] 2022-07-27 12:13
Windows-only bug? `gdb` backtrace would be nice, I guess.

**Comment by flowln** [comment] 2022-07-28 15:05
Can you check if the crash is fixed in 1.4.1?

**Comment by Apocalypsing** [comment] 2022-07-28 18:37
I was facing the same issue with two different modpacks of beta 1.7.3, modpacks that both use jar mods given the age of that game version. Both these instances were crashing PolyMC 1.4.0 consistently when trying to launch, under Windows 10.

Now that I'm running 1.4.1, I launched each of my problematic instances five times just to be sure, and I'm no longer seeing any crashes on my end. 👍

**Comment by DioEgizio** [comment] 2022-08-26 09:23
Can this be closed now?

**Comment by flowln** [comment] 2022-09-06 09:59
Fixed in release 1.4.1 :ok_woman:

**Closed as completed by flowln** 2022-09-06 09:59 UTC
Labels: bug
