### ISSUE TITLE
Download Requires/Related mods

### ISSUE THREAD

**Issue by CitizenFoffie** [PolyMC/PolyMC#910] opened 2022-07-12 23:54 UTC
### Role

I like to download mods quickly without taking a million tabs to also download and find the required mods.

### Suggestion

Selected Related Mods and let me select versions.

### Benefit

It would allow people to not have to find related mods elsewhere

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by nitrog0d** [comment] 2022-07-13 00:01
I was gonna suggest this into an issue, to make Curseforge download the required mods automatically when you download a mod, since someone already did it, I'll ask about my other question too. Would it be possible to add Cursefoge mod update check?

**Comment by DioEgizio** [comment] 2022-07-13 05:30
Duplicate of #211

**Comment by DioEgizio** [comment] 2022-07-13 05:31
> I was gonna suggest this into an issue, to make Curseforge download the required mods automatically when you download a mod, since someone already did it, I'll ask about my other question too. Would it be possible to add Cursefoge mod update check?

Soon™ #588

**Comment by timoreo22** [comment] 2022-07-13 06:42
Duplicate of #211

**Closed as not planned by timoreo22** 2022-07-13 06:42 UTC
Labels: duplicate, enhancement
