### ISSUE TITLE
[Feature Request] Add Ability to upgrade/change mod version within the mod menu itself.

### ISSUE THREAD

**Issue by hydino2085143** [PolyMC/PolyMC#561] opened 2022-05-13 08:28 UTC
### Role

I use different versions of Minecraft mods, and I would like to be able to switch between them in an easy way.

### Suggestion

Add three buttons to the Mods section of Instance Management console:

- an "Update Mod" button which downloads the latest version of the selected mod that is compatible with the current Minecraft version (according to the mod's metadata) and replaces the old mod file with it
- "Change Version" button which allows the user to choose any version of the mod they want. 
- A third button could be added which attempts to update all the mods in the list which can be updated.

### Benefit

This will allow people to keep their (potentially large) mods list up to date without having to enter the Download Mods menu and change versions manually for each mod.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### UI Concept

Here is a UI mockup I have made. All my new buttons have been circled in red.

![image](https://user-images.githubusercontent.com/46134462/168243193-eb003828-6e8e-4838-adbf-d4caa9388ae8.png)

**Comment by DioEgizio** [comment] 2022-05-13 15:00
mod updater is a duplicate of #274 and [it's being worked on](https://github.com/flowln/PolyMC/tree/mod_update)

**Comment by Derpitron** [comment] 2022-05-13 15:49
Thank you, I will close this issue

**Closed by Derpitron** 2022-05-13 15:49 UTC
Labels: enhancement
