### ISSUE TITLE
Add Dependencies to Mod Downloader

### ISSUE THREAD

**Issue by e-splat** [PolyMC/PolyMC#722] opened 2022-06-05 07:56 UTC
### Role

Mod Downloader

### Suggestion

Download Dependencies together with Mods

### Benefit

When i download a mod, i need always to search a compatible version of a dependency

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment] 2022-06-05 08:09
Duplicate of #211

**Closed as not planned** 2022-06-09 21:53 UTC
Labels: duplicate, enhancement
