### ISSUE TITLE
Can't download FTB Direwolf20 1.18 pack

### ISSUE THREAD

**Issue by john01dav** [PolyMC/PolyMC#957] opened 2022-07-23 18:12 UTC
When I try to download the FTB Direwolf20 1.18 pack, it seems to be working but then it eventually stalls and I have this in the CLI output:
```
   38.378 C Task "NetJob(Mod download)" failed:  "Job 'Mod download' failed to process:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
   38.378 C Task "ModpacksCH::PackInstallTask(0x7fb7a0009ee0)" failed:  "Job 'Mod download' failed to process:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
   38.378 C Task "InstanceStaging(0x55571d042b80)" failed:  "Job 'Mod download' failed to process:\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
```

I'm using Fedora Linux 36 Workstation Edition. I tried using a VPN to see if my IP got on a blacklist somehow (my ISP doesn't really stop bad actors, so sometimes the IP range gets on a list), but it did not work so it's unlikely to be that. 

Sometimes, I get this error instead and the download immediately fails:
```
   89.526 C Task "ModpacksCH::PackInstallTask(0x7f0f742fa7a0)" failed:  "Could not understand pack manifest:\n'url's parent does not contain 'url'"
   89.526 C Task "InstanceStaging(0x7f0f744a2830)" failed:  "Could not understand pack manifest:\n'url's parent does not contain 'url'"
```
   
Is FTB trying to stop any launcher other than their's from downloading modpacks again, or is this just a bug?

**Comment by john01dav** [comment] 2022-07-23 18:13
This is happening to at least one other person, so this is probably API breakage.

**Comment by DioEgizio** [comment] 2022-07-23 19:33
Duplicate of https://github.com/PolyMC/PolyMC/issues/955

And yes, it's api breakage. Keep an eye on #699

**Comment by flowln** [comment] 2022-07-28 15:06
Fixed in 1.4.1!

**Closed as completed by flowln** 2022-07-28 15:06 UTC
Labels: bug
