### ISSUE TITLE
PacStall

### ISSUE THREAD

**Issue by Lolothepro** [PolyMC/PolyMC#962] opened 2022-07-24 09:30 UTC
### Role

To allow PolyMC to be used without using Una or Makedeb

### Suggestion

Add a pacstall repository

### Benefit

To allow downloading PolyMC from Pacstall without using una or makedeb.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment] 2022-07-24 09:31
Duplicate of #266

**Closed as completed** 2022-07-24 09:31 UTC
Labels: duplicate, enhancement
