### ISSUE TITLE
`Add .jar` in the mods tabs causes a crash on Wayland

### ISSUE THREAD

**Issue by txtsd** [PolyMC/PolyMC#248] opened 2022-03-10 16:45 UTC
### Operating System

Linux

### Description of bug

Hitting the `Add .jar` button in the mods tab of an instance makes PolyMC crash with this output:
```
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  53 (X_CreatePixmap)
  Serial number of failed request:  13056
  Current serial number in output stream:  13062
```

Launching PolyMC with `QT_QPA_PLATFORM=xcb` makes a file chooser window pop up as expected.

### Steps to reproduce

- Use wayland
- Build and install from `develop`
- Try to `Add .jar` to an instance

### Suspected cause

¯\\_(ツ)\_/¯

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment] 2022-03-20 14:22
Works on my machine:tm:

This is probably a bug with your environment. You shouldn't be getting X errors on Wayland at all

**Comment by Scrumplex** [comment] 2022-03-24 15:52
Can you still reproduce?

**Comment by txtsd** [comment] 2022-03-24 17:40
I rebuilt from source and it works as expected now. Not sure why it was throwing an X error before.

**Comment by 9p4** [comment] 2022-04-22 19:45
I'm building from source (via AUR) and I am now getting this error. The workaround for me is to run the program via `QT_QPA_PLATFORM=xcb polymc` instead.

**Comment by txtsd** [comment] 2022-04-23 10:47
`QT_QPA_PLATFORM=xcb polymc` makes it run in XWayland.

I tried it and it's happening again for me. How do we debug this?

**Comment by Scrumplex** [comment] 2022-04-23 11:01
Run a debug build using `gdb` and when it crashes run `bt full` in the gdb shell

**Comment by txtsd** [comment] 2022-04-23 11:11
On it

**Comment by txtsd** [comment] 2022-04-23 11:58
It doesn't say much. Here's the tail end:

```
[New Thread 0x7fffe37fe640 (LWP 65271)]
   24.468 D Applying "org.lwjgl3" GOOD
   24.468 D Applying "net.minecraft" GOOD
   24.468 D Applying "net.fabricmc.intermediary" GOOD
   24.468 D Applying "net.fabricmc.fabric-loader" GOOD
   24.487 D Downloading  "https://meta.polymc.org/v1/index.json"
   24.487 D Downloading  "https://meta.polymc.org/v1/org.lwjgl3/3.2.2.json"
   24.487 D Downloading  "https://meta.polymc.org/v1/net.minecraft/1.18.1.json"
   24.487 D Downloading  "https://meta.polymc.org/v1/net.fabricmc.intermediary/1.18.1.json"
   24.488 D Downloading  "https://meta.polymc.org/v1/net.fabricmc.fabric-loader/0.13.0.json"
   24.488 D Downloading  "https://meta.polymc.org/v1/org.lwjgl3/index.json"
   24.707 D Download succeeded: "https://meta.polymc.org/v1/index.json"
   24.707 D Task "NetJob(Download of meta file index.json)" succeeded
   24.708 D Remote task 0 succeeded
   24.739 D Download succeeded: "https://meta.polymc.org/v1/org.lwjgl3/3.2.2.json"
   24.739 D Task "NetJob(Download of meta file org.lwjgl3/3.2.2.json)" succeeded
   24.739 D Remote task 1 succeeded
   24.740 D Component list save is scheduled for "Fabric 1.18.1"
   25.118 D Download succeeded: "https://meta.polymc.org/v1/net.fabricmc.intermediary/1.18.1.json"
   25.118 D Task "NetJob(Download of meta file net.fabricmc.intermediary/1.18.1.json)" succeeded
   25.118 D Remote task 3 succeeded
   25.121 D Download succeeded: "https://meta.polymc.org/v1/org.lwjgl3/index.json"
   25.121 D Task "NetJob(Download of meta file org.lwjgl3/index.json)" succeeded
   25.181 D Download succeeded: "https://meta.polymc.org/v1/net.fabricmc.fabric-loader/0.13.0.json"
   25.181 D Task "NetJob(Download of meta file net.fabricmc.fabric-loader/0.13.0.json)" succeeded
   25.181 D Remote task 4 succeeded
   25.416 D Download succeeded: "https://meta.polymc.org/v1/net.minecraft/1.18.1.json"
   25.417 D Task "NetJob(Download of meta file net.minecraft/1.18.1.json)" succeeded
   25.417 D Remote task 2 succeeded
   25.417 D Resolving dependencies
   25.417 D "Req: net.fabricmc.intermediary" Is met.
   25.417 D "Req: net.minecraft == 1.18.1" Is met.
   25.417 D "Req: org.lwjgl3 == 3.2.2" Is met.
   25.417 D Task "ComponentUpdateTask(0x555556499f50)" succeeded
   25.417 D Component list update/resolve task succeeded for "Fabric 1.18.1"
[New Thread 0x7fff82f0e640 (LWP 65276)]
   27.263 D Started watching  "/home/txtsd/.local/share/polymc/instances/1.18/.minecraft/mods"
[New Thread 0x7fff8270d640 (LWP 65277)]
[New Thread 0x7fff81f0c640 (LWP 65278)]
[New Thread 0x7fff8170b640 (LWP 65279)]
[New Thread 0x7fff80f0a640 (LWP 65280)]
[New Thread 0x7fff6bfff640 (LWP 65281)]
[New Thread 0x7fff6b7fe640 (LWP 65282)]
[New Thread 0x7fff6affd640 (LWP 65283)]
   29.957 D Component list save performed now for "Fabric 1.18.1"
[New Thread 0x7fff6a7fc640 (LWP 65288)]
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  53 (X_CreatePixmap)
  Serial number of failed request:  5735
  Current serial number in output stream:  5743
[Thread 0x7fffa67fc640 (LWP 65263) exited]
[Thread 0x7fffa6ffd640 (LWP 65262) exited]
[Thread 0x7fffa77fe640 (LWP 65261) exited]
[Thread 0x7fffa7fff640 (LWP 65260) exited]
[Thread 0x7fffc4ee8640 (LWP 65259) exited]
[Thread 0x7fffc56e9640 (LWP 65258) exited]
[Thread 0x7fffd0d70640 (LWP 65257) exited]
[Thread 0x7fffd1571640 (LWP 65256) exited]
[Thread 0x7fffd1d72640 (LWP 65255) exited]
[Thread 0x7fffd2573640 (LWP 65254) exited]
[Thread 0x7fffe0c1e640 (LWP 65253) exited]
[Thread 0x7fffe1560640 (LWP 65252) exited]
[Thread 0x7fffe27fc640 (LWP 65248) exited]
[Thread 0x7fff6a7fc640 (LWP 65288) exited]
[Thread 0x7fff6affd640 (LWP 65283) exited]
[Thread 0x7fff6b7fe640 (LWP 65282) exited]
[Thread 0x7fff6bfff640 (LWP 65281) exited]
[Thread 0x7fff80f0a640 (LWP 65280) exited]
[Thread 0x7fff8170b640 (LWP 65279) exited]
[Thread 0x7fff81f0c640 (LWP 65278) exited]
[Thread 0x7fff8270d640 (LWP 65277) exited]
[Thread 0x7fff82f0e640 (LWP 65276) exited]
[Thread 0x7fffe37fe640 (LWP 65271) exited]
[Thread 0x7fff83fff640 (LWP 65267) exited]
[Thread 0x7fffa4ff9640 (LWP 65266) exited]
[Thread 0x7fffa57fa640 (LWP 65265) exited]
[Thread 0x7fffa5ffb640 (LWP 65264) exited]
[Thread 0x7fffe2ffd640 (LWP 65247) exited]
[Thread 0x7ffff0bb4640 (LWP 65245) exited]
[Thread 0x7fffe3fff640 (LWP 65244) exited]
[Thread 0x7ffff20cb640 (LWP 65240) exited]
[Thread 0x7ffff28cc640 (LWP 65239) exited]
[Inferior 1 (process 65232) exited with code 01]
```

**Comment by Scrumplex** [comment] 2022-04-23 12:22
@txtsd need the backtrace, after the crash the gdb prompt should re-appear. You should be able to run `bt full` in that prompt to get the full backtrace

**Comment by txtsd** [comment] 2022-04-23 12:53
It just says `No stack.`

**Comment by Scrumplex** [comment] 2022-04-23 12:58
Well that sucks

**Comment by 9p4** [comment] 2022-04-23 18:12
I rebuilt with debugging symbols enabled and the same issue still exists (no stack)

**Comment by 9p4** [comment] 2022-04-29 02:13
I've traced the issue down to `qt5ct` using GTK dialogs. Because `qt5ct` is configured to use GTK2 themes for me, it uses X11 to render some dialog boxes.

This can be fixed by setting the "Standard dialogs" option in `qt5ct` to be `gtk2` instead of `Default`.

This does have the unfortunate side-effect of rendering file-choosers in XWayland.

This isn't a PolyMC issue, but is instead an issue with the Qt theme.

**Comment by txtsd** [comment] 2022-04-29 09:18
Welp. Looks like it's time to migrate away from qt5ct/qt6ct for me.

**Comment by Scrumplex** [comment] 2022-04-29 12:25
I use qt5ct and it works fine for me.

So it should only be relevant if you have that specific setup utilizing GTK2 dialogs

**Comment by txtsd** [comment] 2022-04-29 12:39
Mine is set to `Default`. I don't want to set it to `gtk2` and get XWayland windows.

**Comment by Scrumplex** [comment] 2022-08-26 14:25
If anyone still has issues with this, please check your local Qt installation.

**Closed as not planned by Scrumplex** 2022-08-26 14:25 UTC
Labels: bug, external
